# Generated by Django 2.2 on 2020-09-26 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200912_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='github',
        ),
    ]
